export = Object.freeze({
    HOME_SCREEN_SELECTED_ICON_IMAGE_EXT_ARRAY: ['.jpeg', '.jpg', '.png'],
    HOME_SCREEN_SELECTED_ICON_IMAGE_FILE_SIZE: 5, // 5 MB
    HOME_SCREEN_NON_SELECTED_ICON_IMAGE_EXT_ARRAY: ['.jpeg', '.jpg', '.png'],
    HOME_SCREEN_NON_SELECTED_ICON_IMAGE_FILE_SIZE: 5, // 5 MB
});